# Site
repository: sandipchajjed.github.io
favicon: images/favicon.ico

# Personal info
name: Sandip Chajjed
title: Data Scientist and Analytic Lead
email: sandip.chajjed@carleton.ca
website: sandipchajjed.github.io

darkmode: true

# Social links
twitter_username: SChajjed
github_username:  sandipchajjed
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: sandipchajjed
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/ChajjedS_ss.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi My Name is Sandip Chajjed I like simplicity, and I always strive for excellence. I am a result oriented professional with an aptitude for problem-solving and a passion for data science. I am fascinated with the way data can be transformed into relevant information.

- 4+ years of quantitative experience in research, statistical/mathematical modeling, from both academia and industry.
- Proficient with programming skills such as R, Python, MATLAB, Fortran, C++. An avid learner, learning the new technology every day like SQL, SAS, Tableau.
- Extensive experience and knowledge of statistical/predictive models, numerical algorithms, optimization methods, and data visualizations.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
