# Site
repository: sandipchajjed/sandipchajjed.github.io
favicon: images/favicon.ico
darkmode: true
# Personal info
name: Sandip Chajjed
title: Data Scientist and Analytic Lead
email: sandip.chajjed@carleton.ca
website: https://sandipchajjed.github.io

# Social links
twitter_username: SChajjed
github_username:  sandipchajjed
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sandipchajjed
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/ChajjedS.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sandip and I'm a Data Scientist and Analytic Lead.

  I am most skilled in: <mark>AI</mark> and <mark>Analytics</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Data Science some of my other interests and hobbies are:
   - Reading
   - Meditation
   - cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
